// ⚠️ Generated by rescript-panda. Only edit this file if you want to stop using rescript-panda codegen.
type colors = [
  | #"secondary.light.100"
  | #"secondary.light.200"
  | #"secondary.light.300"
  | #"secondary.dark.100"
  | #"secondary.dark.200"
  | #"secondary.dark.300"
  | #"primary.daciuk.gosta.de.rola"
  | #"primary.100"
  | #"primary.200"
  | #"primary.300"
  | #gray
]
type styles = {
  backgroundColor?: colors,
  borderBottomColor?: colors,
  borderColor?: colors,
  borderLeftColor?: colors,
  borderRightColor?: colors,
  borderTopColor?: colors,
  color?: colors,
  columnRuleColor?: colors,
  outlineColor?: colors,
  textDecorationColor?: colors,
}
@module("@styled/css") external css: styles => string = "css"
