// ⚠️ Generated by rescript-panda. Only edit this file if you want to stop using rescript-panda codegen.
module StyleSystem = {
  type colors = [
    | #"secondary.light.100"
    | #"secondary.light.200"
    | #"secondary.light.300"
    | #"secondary.dark.100"
    | #"secondary.dark.200"
    | #"secondary.dark.300"
    | #"primary.100"
    | #"primary.200"
    | #"primary.300"
    | #"primary.400"
    | #gray
  ]
  type t = {
    backgroundColor?: colors,
    borderBottomColor?: colors,
    borderColor?: colors,
    borderLeftColor?: colors,
    borderRightColor?: colors,
    borderTopColor?: colors,
    color?: colors,
    columnRuleColor?: colors,
    outlineColor?: colors,
    textDecorationColor?: colors,
  }
}
@module("@styled/css") external css: StyleSystem.t => string = "css"
