// ⚠️ Generated by rescript-panda. Only edit this file if you want to stop using rescript-panda codegen.
type colors = [#red | #green | #blue | #primary]
type styles = {color: colors, backgroundColor: colors}
@module("@styled/css") external css: styles => string = "css"
