// Generated by ReScript, PLEASE EDIT WITH CARE


function toColor(v) {
  return v;
}

function rgb(r, g, b) {
  return "[rgb(" + r.toString() + ", " + g.toString() + ", " + b.toString() + ")]";
}

function rgba(r, g, b, a) {
  return "[rgba(" + r.toString() + ", " + g.toString() + ", " + b.toString() + ", " + a.toString() + ")]";
}

function hex(color) {
  return "[" + color + "]";
}

function hsl(h, s, l) {
  return "[hsl(" + h.toString() + ", " + s.toString() + ", " + l.toString() + ")]";
}

function hsla(h, s, l, a) {
  return "[hsla(" + h.toString() + ", " + s.toString() + ", " + l.toString() + ", " + a.toString() + ")]";
}

export {
  toColor ,
  rgb ,
  rgba ,
  hex ,
  hsl ,
  hsla ,
}
/* No side effect */
