// ⚠️ Generated by rescript-panda. Only edit this file if you want to stop using rescript-panda codegen.
type styleObject = {backgroundColor: string, color: string}
@module("@styled/css") external css: styleObject => string = "css"
