exception InvalidPandaConfig(string)

module Process = NodeJs.Process

let createBindingsModule = (config: Config.t) => {
  let disclaimer = "    // ⚠️ Generated by rescript-panda. Only edit this file if you want to stop using rescript-panda codegen."

  let modulePath = NodeJs.Path.join([
    Process.process->Process.cwd,
    config.outdir,
    Constants.mainModuleFileName,
  ])

  let implementation = Generator.generate([StyleSystem.make(config), Css.make(config)])

  let mainFileContent = `
    ${disclaimer}
    ${implementation}
  `

  NodeJs.Fs.writeFileSync(modulePath, mainFileContent->NodeJs.Buffer.fromString)

  NodeJs.ChildProcess.spawnSync(
    "npx",
    ["rescript", "format", "-all"],
    {
      stdio: "ignore",
    },
  )->ignore

  Js.log(
    `✔️ \`${Chalk.green(
        `${config.outdir}/${Constants.mainModuleFileName}`,
      )}\` has been successfully created.`,
  )
}

let run = async () => {
  let config = await Config.get()
  switch config {
  | Ok(config) => createBindingsModule(config)
  | Error(error) =>
    switch error {
    | MissingImportMap =>
      Console.log(
        `⚠️ You forgot to define an ${Chalk.green(
            "importMap",
          )} in your Panda config. \nThe importMap field is required for rescript-panda to generate bindings properly.\n🔎 Check out https://panda-css.com/docs/references/config#importmap`,
      )
    | Otherwise => Console.log("Something went wrong.")
    }
  }
}
