name: Build MacOS
on: [workflow_dispatch]
jobs:
  build_macos:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        ocaml-compiler:
          - 5.2.0

    defaults:
      run:
        working-directory: packages/ppx

    steps:
      - uses: actions/checkout@v4

      - name: Cache OPAM deps
        id: cache-opam
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/opam
            ~/.opam
            _opam
          key: ${{ runner.os }}-opam-${{ hashFiles('**/*.opam') }}-${{ matrix.ocaml-compiler }}
          restore-keys: |
            ${{ runner.os }}-opam-${{ hashFiles('**/*.opam') }}-
            ${{ runner.os }}-opam-

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          working-directory: packages/ppx

      - name: Install deps
        run: |
          opam update
          opam install . --deps-only --with-test
          opam list

      - name: Build
        run: opam exec -- dune build

      - name: Copy built PPX file
        run: |
          mv ./_build/default/bin/bin.exe ppx.exe

      - name: (only on release) Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: packages/ppx/ppx.exe
          if-no-files-found: error
