name: Build Linux
on: [workflow_dispatch]
jobs:
  build_linux:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ocaml-compiler:
          - 5.2.0
    container:
      image: ocaml/opam:alpine-3.16-ocaml-5.2
      options: --user root
    defaults:
      run:
        working-directory: packages/ppx
    steps:
      - uses: actions/checkout@v4
      
      - name: Opam init
        run: opam init -a --disable-sandboxing --compiler=5.2.0

      - name: Install deps
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build --profile static

      - name: Copy built PPX file
        run: |
          mv ./_build/default/bin/bin.exe ppx.exe

      - name: (only on release) Upload artifacts ${{ matrix.os }}
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.os }}
          path: packages/ppx/ppx.exe  # Updated path to include the working directory
          if-no-files-found: error
