module Properties = {
  let colors = [
    "bg",
    "bgColor",
    "backgroundColor",
    "borderColor",
    "borderTopColor",
    "borderLeftColor",
    "borderRightColor",
    "borderBottomColor",
    "borderStartColor",
    "borderInlineStartColor",
    "borderEndColor",
    "borderInlineEndColor",
    "borderXColor",
    "borderInlineColor",
    "borderYColor",
    "borderBlockColor",
    "color",
    "columnRuleColor",
    "outlineColor",
    "textDecorationColor",
  ]

  let spacing = [
    "gap",
    "columnGap",
    "rowGap",
    "gridGap",
    "margin",
    "mt",
    "mb",
    "ml",
    "mr",
    "mx",
    "my",
    "marginTop",
    "marginBottom",
    "marginLeft",
    "marginRight",
    "padding",
    "p",
    "px",
    "py",
    "pt",
    "pb",
    "pl",
    "pr",
    "paddingTop",
    "paddingBottom",
    "paddingLeft",
    "paddingRight",
  ]

  let sizes = ["width", "maxWidth", "minWidth", "height", "maxHeight", "minHeight"]
  let fontFamily = ["fontFamily"]
  let fontWeights = ["fontWeight"]
  let fontSizes = ["fontSize"]
  let letterSpacings = ["letterSpacings"]
  let lineHeights = ["lineHeights"]
  let radii = [
    "rounded",
    "roundedTopLeft",
    "roundedTopRight",
    "roundedBottomRight",
    "roundedBottomLeft",
    "roundedTop",
    "roundedRight",
    "roundedBottom",
    "roundedLeft",
    "borderRadius",
    "borderTopLeftRadius",
    "borderTopRightRadius",
    "borderBottomRightRadius",
    "borderBottomLeftRadius",
    "borderTopRadius",
    "borderRightRadius",
    "borderBottomRadius",
    "borderLeftRadius",
    "roundedStartStart",
    "roundedStartEnd",
    "roundedStart",
    "roundedEndStart",
    "roundedEndEnd",
    "roundedEnd",
    "borderStartStartRadius",
    "borderStartEndRadius",
    "borderStartRadius",
    "borderEndStartRadius",
    "borderEndEndRadius",
    "borderEndRadius",
  ]

  let borders = [
    "border",
    "borderTop",
    "borderRight",
    "borderBottom",
    "borderLeft",
    "outline",
    "borderX",
    "borderInline",
    "borderY",
    "borderBlock",
    "borderStart",
    "borderInlineStart",
    "borderEnd",
    "borderInlineEnd",
  ]
  let borderWidths = [
    "borderWidth",
    "borderTopWidth",
    "borderLeftWidth",
    "borderRightWidth",
    "borderBottomWidth",
    "borderXWidth",
    "borderInlineWidth",
    "borderYWidth",
    "borderBlockWidth",
    "borderStartWidth",
    "borderInlineStartWidth",
    "borderEndWidth",
    "borderInlineEndWidth",
  ]
}
