module Properties = {
  let colors = [
    "bg",
    "bgColor",
    "backgroundColor",
    "borderColor",
    "borderTopColor",
    "borderLeftColor",
    "borderRightColor",
    "borderBottomColor",
    "borderStartColor",
    "borderInlineStartColor",
    "borderEndColor",
    "borderInlineEndColor",
    "borderXColor",
    "borderInlineColor",
    "borderYColor",
    "borderBlockColor",
    "color",
    "columnRuleColor",
    "outlineColor",
    "textDecorationColor",
  ]

  let spacing = [
    "gap",
    "columnGap",
    "rowGap",
    "gridGap",
    "margin",
    "mt",
    "mb",
    "ml",
    "mr",
    "mx",
    "my",
    "marginTop",
    "marginBottom",
    "marginLeft",
    "marginRight",
    "padding",
    "p",
    "px",
    "py",
    "pt",
    "pb",
    "pl",
    "pr",
    "paddingTop",
    "paddingBottom",
    "paddingLeft",
    "paddingRight",
  ]

  let sizes = ["width", "maxWidth", "minWidth", "height", "maxHeight", "minHeight"]
  let fontFamily = ["fontFamily"]
  let fontWeights = ["fontWeight"]
  let fontSizes = ["fontSize"]
  let letterSpacings = ["letterSpacings"]
  let lineHeights = ["lineHeights"]
  let radii = [
    "rounded",
    "roundedTopLeft",
    "roundedTopRight",
    "roundedBottomRight",
    "roundedBottomLeft",
    "roundedTop",
    "roundedRight",
    "roundedBottom",
    "roundedLeft",
    "borderRadius",
    "borderTopLeftRadius",
    "borderTopRightRadius",
    "borderBottomRightRadius",
    "borderBottomLeftRadius",
    "borderTopRadius",
    "borderRightRadius",
    "borderBottomRadius",
    "borderLeftRadius",
    "roundedStartStart",
    "roundedStartEnd",
    "roundedStart",
    "roundedEndStart",
    "roundedEndEnd",
    "roundedEnd",
    "borderStartStartRadius",
    "borderStartEndRadius",
    "borderStartRadius",
    "borderEndStartRadius",
    "borderEndEndRadius",
    "borderEndRadius",
  ]

  let borders = [
    "border",
    "borderTop",
    "borderRight",
    "borderBottom",
    "borderLeft",
    "outline",
    "borderX",
    "borderInline",
    "borderY",
    "borderBlock",
    "borderStart",
    "borderInlineStart",
    "borderEnd",
    "borderInlineEnd",
  ]
  let borderWidths = [
    "borderWidth",
    "borderTopWidth",
    "borderLeftWidth",
    "borderRightWidth",
    "borderBottomWidth",
    "borderXWidth",
    "borderInlineWidth",
    "borderYWidth",
    "borderBlockWidth",
    "borderStartWidth",
    "borderInlineStartWidth",
    "borderEndWidth",
    "borderInlineEndWidth",
  ]

  let shadows = ["boxShadow"]
  let easings = ["transitionTimingFunction"]
  let opacity = ["opacity"]
  let zIndex = ["zIndex"]
  let durations = ["transitionDuration", "animationDuration"]
  let assets = ["backgroundImage"]
  let animations = ["animation"]

  module Commons = {
    type property = {
      keys: array<string>,
      values: array<string>,
      typeName: string,
    }

    let allProperties = [
      // Keeping your existing display property
      {
        typeName: "display",
        keys: ["display"],
        values: [
          "block",
          "inline",
          "run-in",
          "flow",
          "flow-root",
          "table",
          "flex",
          "grid",
          "ruby",
          "list-item",
          "contents",
          "none",
          "inline-block",
          "inline-table",
          "inline-flex",
          "inline-grid",
          "table-row-group",
          "table-header-group",
          "table-footer-group",
          "table-row",
          "table-cell",
          "table-column-group",
          "table-column",
          "table-caption",
          "ruby-base",
          "ruby-text",
          "ruby-base-container",
          "ruby-text-container",
          "inherit",
          "initial",
          "revert",
          "revert-layer",
          "unset",
        ],
      },
      {
        typeName: "alignContent",
        keys: ["alignContent"],
        values: [
          "normal",
          "center",
          "start",
          "end",
          "flex-start",
          "flex-end",
          "baseline",
          "first baseline",
          "last baseline",
          "space-between",
          "space-around",
          "space-evenly",
          "stretch",
          "inherit",
          "initial",
          "unset",
        ],
      },
      {
        typeName: "alignItems",
        keys: ["alignItems"],
        values: [
          "normal",
          "stretch",
          "center",
          "start",
          "end",
          "flex-start",
          "flex-end",
          "baseline",
          "first baseline",
          "last baseline",
          "inherit",
          "initial",
          "unset",
        ],
      },
      {
        typeName: "alignSelf",
        keys: ["alignSelf"],
        values: [
          "auto",
          "normal",
          "center",
          "start",
          "end",
          "self-start",
          "self-end",
          "flex-start",
          "flex-end",
          "baseline",
          "first baseline",
          "last baseline",
          "stretch",
          "inherit",
          "initial",
          "unset",
        ],
      },
      {
        typeName: "all",
        keys: ["all"],
        values: ["initial", "inherit", "unset", "revert", "revert-layer"],
      },
      {
        typeName: "animationComposition",
        keys: ["animationComposition"],
        values: ["replace", "add", "accumulate"],
      },
      {
        typeName: "animationDirection",
        keys: ["animationDirection"],
        values: ["normal", "reverse", "alternate", "alternate-reverse"],
      },
      {
        typeName: "animationFillMode",
        keys: ["animationFillMode"],
        values: ["none", "forwards", "backwards", "both"],
      },
      {
        typeName: "appearance",
        keys: ["appearance"],
        values: [
          "none",
          "auto",
          "button",
          "textfield",
          "searchfield",
          "textarea",
          "push-button",
          "slider-horizontal",
          "checkbox",
          "radio",
          "square-button",
          "menulist",
          "menulist-button",
          "listbox",
          "meter",
          "progress-bar",
        ],
      },
      {
        typeName: "backfaceVisibility",
        keys: ["backfaceVisibility"],
        values: ["visible", "hidden"],
      },
      {
        typeName: "backgroundAttachment",
        keys: ["backgroundAttachment"],
        values: ["scroll", "fixed", "local", "inherit"],
      },
      {
        typeName: "backgroundClip",
        keys: ["backgroundClip"],
        values: ["border-box", "padding-box", "content-box", "text"],
      },
      {
        typeName: "borderCollapse",
        keys: ["borderCollapse"],
        values: ["collapse", "separate", "inherit"],
      },
      {
        typeName: "borderStyle",
        keys: [
          "borderBlockEndStyle",
          "borderBlockStartStyle",
          "borderBlockStyle",
          "borderBottomStyle",
          "borderInlineEndStyle",
          "borderInlineStartStyle",
          "borderInlineStyle",
          "borderLeftStyle",
          "borderRightStyle",
          "borderTopStyle",
        ],
        values: [
          "none",
          "hidden",
          "dotted",
          "dashed",
          "solid",
          "double",
          "groove",
          "ridge",
          "inset",
          "outset",
        ],
      },
      {
        typeName: "boxDecorationBreak",
        keys: ["boxDecorationBreak"],
        values: ["slice", "clone"],
      },
      {
        typeName: "boxSizing",
        keys: ["boxSizing"],
        values: ["content-box", "border-box"],
      },
      {
        typeName: "break",
        keys: ["breakAfter", "breakBefore", "breakInside"],
        values: [
          "auto",
          "avoid",
          "always",
          "all",
          "avoid-page",
          "page",
          "left",
          "right",
          "recto",
          "verso",
          "avoid-column",
          "column",
          "avoid-region",
          "region",
        ],
      },
      {
        typeName: "captionSide",
        keys: ["captionSide"],
        values: ["top", "bottom", "inherit"],
      },
      {
        typeName: "clear",
        keys: ["clear"],
        values: ["none", "left", "right", "both", "inherit"],
      },
      {
        typeName: "columnFill",
        keys: ["columnFill"],
        values: ["auto", "balance", "balance-all"],
      },
      {
        typeName: "columnRuleStyle",
        keys: ["columnRuleStyle"],
        values: [
          "none",
          "hidden",
          "dotted",
          "dashed",
          "solid",
          "double",
          "groove",
          "ridge",
          "inset",
          "outset",
        ],
      },
      {
        typeName: "contentVisibility",
        keys: ["contentVisibility"],
        values: ["visible", "hidden", "auto"],
      },
      {
        typeName: "direction",
        keys: ["direction"],
        values: ["ltr", "rtl", "inherit"],
      },
      {
        typeName: "emptyCells",
        keys: ["emptyCells"],
        values: ["show", "hide", "inherit"],
      },
      {
        typeName: "flexDirection",
        keys: ["flexDirection"],
        values: ["row", "row-reverse", "column", "column-reverse"],
      },
      {
        typeName: "flexWrap",
        keys: ["flexWrap"],
        values: ["nowrap", "wrap", "wrap-reverse"],
      },
      {
        typeName: "float_",
        keys: ["float_"],
        values: ["left", "right", "none", "inline-start", "inline-end", "inherit"],
      },
      {
        typeName: "fontKerning",
        keys: ["fontKerning"],
        values: ["auto", "normal", "none"],
      },
      {
        typeName: "forcedColorAdjust",
        keys: ["forcedColorAdjust"],
        values: ["auto", "none"],
      },
      {
        typeName: "isolation",
        keys: ["isolation"],
        values: ["auto", "isolate"],
      },
      {
        typeName: "lineBreak",
        keys: ["lineBreak"],
        values: ["auto", "loose", "normal", "strict", "anywhere"],
      },
      {
        typeName: "mixBlendMode",
        keys: ["mixBlendMode"],
        values: [
          "normal",
          "multiply",
          "screen",
          "overlay",
          "darken",
          "lighten",
          "color-dodge",
          "color-burn",
          "hard-light",
          "soft-light",
          "difference",
          "exclusion",
          "hue",
          "saturation",
          "color",
          "luminosity",
        ],
      },
      {
        typeName: "objectFit",
        keys: ["objectFit"],
        values: ["fill", "contain", "cover", "none", "scale-down"],
      },
      {
        typeName: "outlineStyle",
        keys: ["outlineStyle"],
        values: [
          "auto",
          "none",
          "dotted",
          "dashed",
          "solid",
          "double",
          "groove",
          "ridge",
          "inset",
          "outset",
        ],
      },
      {
        typeName: "overflow",
        keys: ["overflow", "overflowX", "overflowY", "overflowBlock", "overflowInline"],
        values: ["visible", "hidden", "scroll", "auto", "clip"],
      },
      {
        typeName: "overflowWrap",
        keys: ["overflowWrap"],
        values: ["normal", "break-word", "anywhere"],
      },
      {
        typeName: "pointerEvents",
        keys: ["pointerEvents"],
        values: [
          "auto",
          "none",
          "visiblePainted",
          "visibleFill",
          "visibleStroke",
          "visible",
          "painted",
          "fill",
          "stroke",
          "all",
        ],
      },
      {
        typeName: "position",
        keys: ["position"],
        values: ["static", "relative", "absolute", "fixed", "sticky"],
      },
      {
        typeName: "resize",
        keys: ["resize"],
        values: ["none", "both", "horizontal", "vertical", "block", "inline"],
      },
      {
        typeName: "scrollBehavior",
        keys: ["scrollBehavior"],
        values: ["auto", "smooth"],
      },
      {
        typeName: "touchAction",
        keys: ["touchAction"],
        values: [
          "auto",
          "none",
          "pan-x",
          "pan-left",
          "pan-right",
          "pan-y",
          "pan-up",
          "pan-down",
          "pinch-zoom",
          "manipulation",
        ],
      },
      {
        typeName: "transformBox",
        keys: ["transformBox"],
        values: ["content-box", "border-box", "fill-box", "stroke-box", "view-box"],
      },
      {
        typeName: "transformStyle",
        keys: ["transformStyle"],
        values: ["flat", "preserve-3d"],
      },
      {
        typeName: "userSelect",
        keys: ["userSelect"],
        values: ["none", "auto", "text", "contain", "all"],
      },
      {
        typeName: "visibility",
        keys: ["visibility"],
        values: ["visible", "hidden", "collapse"],
      },
      {
        typeName: "wordBreak",
        keys: ["wordBreak"],
        values: ["normal", "break-all", "keep-all", "break-word"],
      },
      {
        typeName: "writingMode",
        keys: ["writingMode"],
        values: ["horizontal-tb", "vertical-rl", "vertical-lr"],
      },
    ]
  }
}
