let propertiesThatUseColors = [
  "bg",
  "backgroundColor",
  "borderBottomColor",
  "borderColor",
  "borderLeftColor",
  "borderRightColor",
  "borderTopColor",
  "color",
  "columnRuleColor",
  "outlineColor",
  "textDecorationColor",
]

let propertiesThatUseSpcing = [
  "gap",
  "columnGap",
  "rowGap",
  "gridGap",
  "margin",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "padding",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
]
